<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
class MProdukTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('m_produk')->truncate();
        DB::table('m_produk')->insert([
            [
                'm_produk_code' =>'tl-100001',
                'm_produk_nama' => 'plastik tong sampah',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>1,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'tl-100002',
                'm_produk_nama' => 'kresek jumbo sampah',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>1,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'tl-100002',
                'm_produk_nama' => 'kresek jumbo sampah',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>1,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'tl-100003',
                'm_produk_nama' => 'plastik 1kg',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>1,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'tl-100004',
                'm_produk_nama' => 'plastik 1/2kg',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>1,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'tl-100005',
                'm_produk_nama' => 'deterjen',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>1,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'tl-100006',
                'm_produk_nama' => 'sabun cair',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>1,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'tl-100007',
                'm_produk_nama' => 'sabun colek',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>1,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'tl-100008',
                'm_produk_nama' => 'daun pisang',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>1,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'tl-100009',
                'm_produk_nama' => 'kertas bungkus nasi',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>1,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'tl-100010',
                'm_produk_nama' => 'sendok plastik nasi doos',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>1,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bo-200001',
                'm_produk_nama' => 'kresek kecil',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>2,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>2,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bo-200002',
                'm_produk_nama' => 'kresek tanggung',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>2,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>2,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bo-200003',
                'm_produk_nama' => 'handsoap',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>2,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>2,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bo-200004',
                'm_produk_nama' => 'pembersih lantai',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>2,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>2,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bo-200005',
                'm_produk_nama' => 'pipet',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>2,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>2,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bo-200006',
                'm_produk_nama' => 'tisu makan',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>2,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>2,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bo-200007',
                'm_produk_nama' => 'tusuk gigi',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>2,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>2,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bo-200008',
                'm_produk_nama' => 'kamper gantung',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>2,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>2,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bo-200009',
                'm_produk_nama' => 'pengharum ruangan',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1, 
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>2,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>2,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bo-200010',
                'm_produk_nama' => 'pengharum ruangan',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>2,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>2,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bb-300001',
                'm_produk_nama' => 'asem',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bb-300002',
                'm_produk_nama' => 'alpukat',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bb-300003',
                'm_produk_nama' => 'ayam dada',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bb-300004',
                'm_produk_nama' => 'ayam paha',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bb-300005',
                'm_produk_nama' => 'ayam kampung paha',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bb-300006',
                'm_produk_nama' => 'ayam kampung dada',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bb-300007',
                'm_produk_nama' => 'cumi',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bb-300008',
                'm_produk_nama' => 'udang',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bb-300009',
                'm_produk_nama' => 'bawang merah',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bb-300010',
                'm_produk_nama' => 'bawang putih',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bb-300011',
                'm_produk_nama' => 'beras c4',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'bb-300012',
                'm_produk_nama' => 'beras mentik',
                'm_produk_urut' => '000-001',
                'm_produk_cr' => 1,
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>4,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'tidak',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400001',
                'm_produk_nama' => 'Sambal Bajak',
                'm_produk_urut' => '001-001',
                'm_produk_cr' => 'Sambal Bajak',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400002',
                'm_produk_nama' => 'Sambal Bawang',
                'm_produk_urut' => '001-002',
                'm_produk_cr' => 'Sambal Bawang',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400003',
                'm_produk_nama' => 'Sambal Bawang Jos',
                'm_produk_urut' => '001-003',
                'm_produk_cr' => 'Sambal Bawang Jos',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400004',
                'm_produk_nama' => 'Sambal Bawang Bakar',
                'm_produk_urut' => '001-004',
                'm_produk_cr' => 'Sambal Bawang Bakar',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400005',
                'm_produk_nama' => 'Sambal Bawang Goreng',
                'm_produk_urut' => '001-005',
                'm_produk_cr' => 'Sambal Bawang Goreng',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400006',
                'm_produk_nama' => 'Sambal Bawang Tomat',
                'm_produk_urut' =>' 001-006',
                'm_produk_cr' => 'Sambal Bawang Tomat',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400007',
                'm_produk_nama' => 'Sambal Bawang Brambang Goreng',
                'm_produk_urut' => '001-007',
                'm_produk_cr' => 'Sambal Bawang Brambang Goreng',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400008',
                'm_produk_nama' => 'Sambal Matah',
                'm_produk_urut' => '001-007',
                'm_produk_cr' => 'Sambal Matah',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400009',
                'm_produk_nama' => 'Sambal Gobal-Gabul',
                'm_produk_urut' => '001-009',
                'm_produk_cr' => 'Sambal Gobal-Gabul',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400010',
                'm_produk_nama' => 'Sambal Kecap',
                'm_produk_urut' =>'001-010',
                'm_produk_cr' => 'Sambal Kecap',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400011',
                'm_produk_nama' => 'Sambal Bawang Lombok Ijo',
                'm_produk_urut' =>'001-011',
                'm_produk_cr' => 'Sambal Bawang Lombok Ijo',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400012',
                'm_produk_nama' => 'Sambal Mangga Muda',
                'm_produk_urut' =>'001-012',
                'm_produk_cr' => 'Sambal Mangga Muda',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400013',
                'm_produk_nama' => 'Sambal Nanas',
                'm_produk_urut' =>'001-013',
                'm_produk_cr' => 'Sambal Nanas',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400014',
                'm_produk_nama' => 'Sambal Tomat Trasi Matang',
                'm_produk_urut' =>'001-014',
                'm_produk_cr' => 'Sambal Tomat Trasi Matang',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400015',
                'm_produk_nama' => 'Sambal Trasi Lombok Ijo',
                'm_produk_urut' =>'001-015',
                'm_produk_cr' => 'Sambal Trasi Lombok Ijo',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400016',
                'm_produk_nama' => 'Sambal Trasi Matang',
                'm_produk_urut' =>'001-016',
                'm_produk_cr' => 'Sambal Trasi Matang',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400017',
                'm_produk_nama' => 'Sambal Trasi Segar',
                'm_produk_urut' =>'001-017',
                'm_produk_cr' => 'Sambal Trasi Segar',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'	mn-400018',
                'm_produk_nama' => 'Sambal Trasi Tomat Segar',
                'm_produk_urut' =>'001-018',
                'm_produk_cr' => 'Sambal Trasi Tomat Segar',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400019',
                'm_produk_nama' => 'Sambal Trasi Brambang Tomat',
                'm_produk_urut' =>'001-019',
                'm_produk_cr' => 'Sambal Trasi Brambang Tomat',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400020',
                'm_produk_nama' => 'Sambal Belut',
                'm_produk_urut' =>'001-020',
                'm_produk_cr' => 'Sambal Belut',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400021',
                'm_produk_nama' => 'Ayam Pedas Gobal-Gabul',
                'm_produk_urut' =>'002-001',
                'm_produk_cr' => 'Ayam Pedas Gobal-Gabul',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>4,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>5,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'sales',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400022',
                'm_produk_nama' => 'Ayam Kampung Dada (Goreng)',
                'm_produk_urut' =>'002-002',
                'm_produk_cr' => 'Ayam Kampung Dada (Goreng)',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>4,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>1,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'sales',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400023',
                'm_produk_nama' => 'Ayam Kampung Dada (Bakar)',
                'm_produk_urut' =>'002-003',
                'm_produk_cr' => 'Ayam Kampung Dada (Bakar)',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>4,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>7,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'sales',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400024',
                'm_produk_nama' => 'Ayam Kampung Paha (Goreng)',
                'm_produk_urut' =>'002-004',
                'm_produk_cr' => 'Ayam Kampung Paha (Goreng)',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>4,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>1,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'sales',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400025',
                'm_produk_nama' => 'Bebek Dada (Goreng)',
                'm_produk_urut' =>'002-013',
                'm_produk_cr' => 'Bebek Dada (Goreng)',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>4,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>1,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'sales',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400026',
                'm_produk_nama' => 'Bebek Paha (Goreng)',
                'm_produk_urut' =>'002-015',
                'm_produk_cr' => 'Bebek Paha (Goreng)',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>4,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>1,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'sales',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400027',
                'm_produk_nama' => 'Belut Sawah Polos',
                'm_produk_urut' =>'002-017',
                'm_produk_cr' => 'Belut Sawah Polos',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>4,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>1,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'sales',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400028',
                'm_produk_nama' => 'Ikan Bandeng (Goreng)',
                'm_produk_urut' =>'002-018',
                'm_produk_cr' => 'Ikan Bandeng (Goreng)',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>4,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>1,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'sales',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400029',
                'm_produk_nama' => 'Ikan Gurame (Goreng)',
                'm_produk_urut' =>'002-022',
                'm_produk_cr' => 'Ikan Gurame (Goreng)',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>4,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>1,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'sales',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400030',
                'm_produk_nama' => 'Ikan Gurame (Goreng)',
                'm_produk_urut' =>'002-022',
                'm_produk_cr' => 'Ikan Gurame (Goreng)',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>4,
                'm_produk_utama_m_satuan_id'=>4,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>1,
                'm_produk_m_klasifikasi_produk_id'=>4,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'sales',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400031',
                'm_produk_nama' => 'Ayam Negeri Dada Asin Frozen',
                'm_produk_urut' =>'000-001',
                'm_produk_cr' => 'Ayam Negeri Dada Asin Frozen',
                'm_produk_status'=>1,
                'm_produk_tax'=> 0,
                'm_produk_sc'=> 0,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>3,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>0,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'mn-400032',
                'm_produk_nama' => 'Bumbu Tabur Bawang',
                'm_produk_urut' =>'000-002',
                'm_produk_cr' => 'Bumbu Tabur Bawang',
                'm_produk_status'=>1,
                'm_produk_tax'=> 0,
                'm_produk_sc'=>0,
                'm_produk_m_jenis_produk_id'=>1,
                'm_produk_utama_m_satuan_id'=>1,
                'm_produk_produksi_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>0,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'ya',
                'm_produk_scp'=>'ya',
                'm_produk_hpp'=>'scp',
                'm_produk_created_by'=>'1',
            ],
        ]);
    }
}