<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
class MProdukTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('m_produk')->truncate();
        DB::table('m_produk')->insert([
            [
                'm_produk_code' =>'FG-11-000-018',
                'm_produk_nama' => 'Sambal Bajak',
                'm_produk_urut' => '001-001',
                'm_produk_cr' => 'Sambal Bajak',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>4,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'Ya',
                'm_produk_scp'=>'Ya',
                'm_produk_hpp'=>'Scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'FG-11-000-009',
                'm_produk_nama' => 'Sambal Bawang',
                'm_produk_urut' => '001-002',
                'm_produk_cr' => 'Sambal Bawang',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'Ya',
                'm_produk_scp'=>'Ya',
                'm_produk_hpp'=>'Scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'FG-11-000-060',
                'm_produk_nama' => 'Sambal Bawang Jos',
                'm_produk_urut' => '001-003',
                'm_produk_cr' => 'Sambal Bawang Jos',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'Ya',
                'm_produk_scp'=>'Ya',
                'm_produk_hpp'=>'Scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'FG-11-000-035',
                'm_produk_nama' => 'Sambal Bawang Bakar',
                'm_produk_urut' => '001-004',
                'm_produk_cr' => 'Sambal Bawang Bakar',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'Ya',
                'm_produk_scp'=>'Ya',
                'm_produk_hpp'=>'Scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'FG-11-000-010',
                'm_produk_nama' => 'Sambal Bawang Goreng',
                'm_produk_urut' => '001-005',
                'm_produk_cr' => 'Sambal Bawang Goreng',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'Ya',
                'm_produk_scp'=>'Ya',
                'm_produk_hpp'=>'Scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'	FG-11-000-011',
                'm_produk_nama' => 'Sambal Bawang Tomat',
                'm_produk_urut' =>' 001-006',
                'm_produk_cr' => 'Sambal Bawang Tomat',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'Ya',
                'm_produk_scp'=>'Ya',
                'm_produk_hpp'=>'Scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'	FG-11-000-026',
                'm_produk_nama' => 'Sambal Bawang Brambang Goreng',
                'm_produk_urut' => '001-007',
                'm_produk_cr' => 'Sambal Bawang Brambang Goreng',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'Ya',
                'm_produk_scp'=>'Ya',
                'm_produk_hpp'=>'Scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'	FG-11-000-044',
                'm_produk_nama' => 'Sambal Matah',
                'm_produk_urut' => '001-007',
                'm_produk_cr' => 'Sambal Bawang Brambang Goreng',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'Ya',
                'm_produk_scp'=>'Ya',
                'm_produk_hpp'=>'Scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'	FG-11-000-020',
                'm_produk_nama' => 'Sambal Gobal-Gabul',
                'm_produk_urut' => '001-009',
                'm_produk_cr' => 'Sambal Gobal-Gabul',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>4,
                'm_produk_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'Ya',
                'm_produk_scp'=>'Ya',
                'm_produk_hpp'=>'Scp',
                'm_produk_created_by'=>'1',
            ],
            [
                'm_produk_code' =>'FG-11-000-015',
                'm_produk_nama' => 'Sambal Kecap',
                'm_produk_urut' =>'001-010',
                'm_produk_cr' => 'Sambal Kecap',
                'm_produk_status'=> 1,
                'm_produk_tax'=> 1,
                'm_produk_sc'=> 1,
                'm_produk_m_jenis_produk_id'=>3,
                'm_produk_m_satuan_id'=>1,
                'm_produk_m_plot_produksi_id'=>3,
                'm_produk_m_klasifikasi_produk_id'=>3,
                'm_produk_jual'=>'Ya',
                'm_produk_scp'=>'Ya',
                'm_produk_hpp'=>'Scp',
                'm_produk_created_by'=>'1',
            ],
        ]);
    }
}