<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
class MWTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('m_w')->truncate();
        DB::table('m_w')->insert([
            [  
                'm_w_nama' =>'WSS Wonosobo',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jln Raya Parakan - Wonosobo No.23 Karangluhur, Kenteng, Bojasari,Kec. Kertek, Kabupaten Wonosobo, Jawa Tengah 56371',
                'm_w_m_jenis_nota_id'=>96,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Tasikmalaya',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'	Jl. Sutisna Senjaya No. 189 Kel. Cikalang, Kec. Tawang, Tasikmalaya',
                'm_w_m_jenis_nota_id'=>25,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Tegal',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kapten Soedibyo No 220 , Tegal Selatan, Tegal',
                'm_w_m_jenis_nota_id'=>89,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS GOR Satria',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Prof. DR. Soeharso, (Depan Pintu Barat GOR Satria), Purwokerto',
                'm_w_m_jenis_nota_id'=>78,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS WSS Cirebon Ampera',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Ampera Raya No.11A, Pekiringan, Kesambi, Kota Cirebon',
                'm_w_m_jenis_nota_id'=>36,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Cirebon Tuparev',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Tuparev (Samping Sentral Yamaha), Kesambi, Cirebon',
                'm_w_m_jenis_nota_id'=>37,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Wiryaatmaja',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. RA. Wiryaatmaja (Jl. Bank) Kel Kedungwuluh, Purwokerto Barat',
                'm_w_m_jenis_nota_id'=>79,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Cilacap',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl MT Haryono No.31 (Sebelah DISHUB), Cilacap Selatan',
                'm_w_m_jenis_nota_id'=>35,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bali Gatot Subroto',
                'm_w_m_area_id'=>8,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Gatot Subroto Barat No.456, Padangsambian Kaja, Kec. Denpasar Bar., Kota Denpasar, Bali 80118',
                'm_w_m_jenis_nota_id'=>5,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Teuku Umar',
                'm_w_m_area_id'=>8,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Teuku Umar Barat No. 355, Denpasar, Bali',
                'm_w_m_jenis_nota_id'=>2,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bali Batubulan',
                'm_w_m_area_id'=>8,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Raya Batubulan - Gianyar (utara Lapangan Candra Muka), Batubulan, Gianyar',
                'm_w_m_jenis_nota_id'=>4,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bali Tukad Barito',
                'm_w_m_area_id'=>8,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Tukad Barito No. 30-31 Renon, Denpasar',
                'm_w_m_jenis_nota_id'=>3,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bali Uluwatu',
                'm_w_m_area_id'=>8,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Pura Masuka no. 1, Ungasan, Uluwatu, Badung Selatan, Bali',
                'm_w_m_jenis_nota_id'=>1,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Depok Sawangan',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Raya Sawangan No.63, Mampang, Kec. Pancoran Mas, Kota Depok, Jawa Barat 16435',
                'm_w_m_jenis_nota_id'=>15,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bogor Ahmad Yani',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Ahmad Yani No 76 RT 02/02 Kel. Tanah Sareal Kec. Tanah Sareal-Kota Bogor-Jawa Barat',
                'm_w_m_jenis_nota_id'=>11,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kisamaun 1',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kisamaun No 233, Sukasari, Tangerang.',
                'm_w_m_jenis_nota_id'=>19,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kisamaun 2',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kisamaun No 233 Pasar Lama, Tangerang (Depan PDAM)',
                'm_w_m_jenis_nota_id'=>20,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS BSD',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Bumi Serpong Damai Blok V2/23 sektor 1.2 Tangerang',
                'm_w_m_jenis_nota_id'=>12,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Karawaci',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Ruko Asiatic JI. Permata Sari B15 No 50, Karawaci, Tangerang',
                'm_w_m_jenis_nota_id'=>18,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bintaro 1',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'JI. Bintaro Utama III Blok AP No 57 Bintaro Sektor 3, Tangerang',
                'm_w_m_jenis_nota_id'=>8,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bintaro 2',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Bintaro Utama III Blok AP No.58 Bintaro Sektor 3, Tangerang.',
                'm_w_m_jenis_nota_id'=>9,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Citra Raya',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Ruko Blossom Ville W1 No 20 Citra Raya, Tangerang',
                'm_w_m_jenis_nota_id'=>13,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Agricola',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'JI. Agricola, Ruko Agricola Blok A15, Kelapa Dua, Curug sangereng, Tangerang',
                'm_w_m_jenis_nota_id'=>21,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Gading Serpong',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'JI Raya Kelapa Puan AF1/19 Ruko Gading Serpong Summarecon, Tangerang',
                'm_w_m_jenis_nota_id'=>16,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bogor Yasmin',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Ruko Taman Yasmin, Jl. RKH Abdulah Bin Nuh No 202 Sektor 6, Bogor Barat, Bogor',
                'm_w_m_jenis_nota_id'=>10,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Greenville',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jln. Greenvile Blok BL No.3, Duri Kepa, Kebon Jeruk, Jakarta Barat',
                'm_w_m_jenis_nota_id'=>17,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Greenville',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jln. Greenvile Blok BL No.3, Duri Kepa, Kebon Jeruk, Jakarta Barat',
                'm_w_m_jenis_nota_id'=>17,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Palemsemi',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Parasel Ruko Madrid No 30. Palemsemi, Karawaci, Tangerang',
                'm_w_m_jenis_nota_id'=>22,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Tanjung Duren Utara',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Tanjung Duren Utara No. 224 Grogol-Jakarta Barat',
                'm_w_m_jenis_nota_id'=>24,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bekasi',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Jend. Sudirman No. 16, Kayuringin Jaya, Bekasi Selatan Jawa Barat',
                'm_w_m_jenis_nota_id'=>7,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Tamansari',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Pusat Kuliner Tamansari, Jl. Boulevard Palem Raya, Lippo Karawaci, Tangerang',
                'm_w_m_jenis_nota_id'=>23,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Jatinangor',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kol. Ahmad Sam No.48 Desa Sayang, Jatinangor, Sumedang',
                'm_w_m_jenis_nota_id'=>97,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bawean',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Bawean No.1, Merdeka, Sumur Bandung, Kota Bandung, Jawa Barat.',
                'm_w_m_jenis_nota_id'=>6,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Depok',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Margonda Raya No.280, Kemiri Muka, Beji, Kota Depok',
                'm_w_m_jenis_nota_id'=>14,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kediri',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Letjend Suparman No.60, Tosaren,  Kota Kediri',
                'm_w_m_jenis_nota_id'=>47,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Malang Sengkaling',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Sengkaling No. 150, Malang',
                'm_w_m_jenis_nota_id'=>62,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Malang Sengkaling',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Sengkaling No. 150, Malang',
                'm_w_m_jenis_nota_id'=>62,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Malang Ciliwung',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Ciliwung No. 53, Malang',
                'm_w_m_jenis_nota_id'=>60,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Jember',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Danau Toba No. 15, Tegal Gede, Sumber, Jember',
                'm_w_m_jenis_nota_id'=>44,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Madiun',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. H. Agus Salim No. 180, Manguharjo, Madiun',
                'm_w_m_jenis_nota_id'=>57,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Arjuna Raya',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Arjuna Raya Gg. Merapi No. 12-14, Sawahan',
                'm_w_m_jenis_nota_id'=>26,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Rungkut',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jalan Rungkut Madya no. 25, Rungkut Kidul, Surabaya',
                'm_w_m_jenis_nota_id'=>27,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Malang LA Sucipto',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Laksda Adi Sucipto No.75, Jawa Timur 65125',
                'm_w_m_jenis_nota_id'=>61,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kulonprogo',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kolonel Sugiono No.16, Gadingan, Wates, Kulon Progo, Yogyakarata 55651',
                'm_w_m_jenis_nota_id'=>53,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Ambarketawang',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Wates No.Km 6, Depok, Ambarketawang, Kec. Gamping, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55293',
                'm_w_m_jenis_nota_id'=>28,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Jakal Km 12',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kaliurang Km. 12 No. 42 Sardonoharjo, Ngaglik, Sleman, Yogyakarta',
                'm_w_m_jenis_nota_id'=>43,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Tekim',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Universitas Gajah Mada',
                'm_w_m_jenis_nota_id'=>98,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Sewon',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Parangtritis Km. 9 Sewon, Bantul, Yogyakarta',
                'm_w_m_jenis_nota_id'=>85,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Magelang',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jalan Tentara Pelajar No. 20, Kemirirejo, Magelang',
                'm_w_m_jenis_nota_id'=>58,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Prambanan',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jalan Raya Jogja - Solo, Sri Mulyo, Kebondalem Kidul, Prambanan',
                'm_w_m_jenis_nota_id'=>76,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Palagan',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Palagan Tentara Pelajar km.7 no. 20A, Yogyakarta.',
                'm_w_m_jenis_nota_id'=>69,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Wonosari',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Baron Km 1, Siraman, Wonosari, Yogyakarta',
                'm_w_m_jenis_nota_id'=>95,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Temanggung',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jln Gatot Subroto no.30 Manding,temanggung,temanggung',
                'm_w_m_jenis_nota_id'=>90,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kupatan',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Ahmad Yani 340 Magelang (Depan RSJ Dr. Soerojo)',
                'm_w_m_jenis_nota_id'=>54,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Muntilan',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Bima,Sayangan, Muntilan, Kauman, Muntilan, Magelang',
                'm_w_m_jenis_nota_id'=>67,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Sompok',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Sompok No 22, Semarang Selatan, Semarang',
                'm_w_m_jenis_nota_id'=>87,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Banyumanik',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jalan Durian Selatan I No. 29, Srondol Wetan, Banyumanik, Semarang',
                'm_w_m_jenis_nota_id'=>31,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Puri Anjasmoro',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Puri Anjasmoro Raya No 49, Semarang Barat, Semarang',
                'm_w_m_jenis_nota_id'=>77,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Sambiroto',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Sambiroto Raya No F5 (Ruko Sambiroto) Semarang',
                'm_w_m_jenis_nota_id'=>82,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Lampersari',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Lamper Sari No.29, Lamper Kidul, Semarang Selatan, Kota Semarang',
                'm_w_m_jenis_nota_id'=>56,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Ngaliyan',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Prof. Dr Hamka No 59, Semarang Barat,Ngaliyan, Semarang',
                'm_w_m_jenis_nota_id'=>68,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Salatiga Diponegoro',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Diponegoro No 105, Ruko wijaya Square A1, Sidorejo, Kota Salatiga',
                'm_w_m_jenis_nota_id'=>80,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Salatiga Sudirman',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Jend. Sudirman No 286, Mrican, Salatiga',
                'm_w_m_jenis_nota_id'=>81,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Pekalongan',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Sapu Garut no. 130, Buaran, Pekalongan',
                'm_w_m_jenis_nota_id'=>74,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Ungaran',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Gatot Subroto No 6 (Jl.Raya Ungaran-Semarang), Bandarjo, Ungaran barat',
                'm_w_m_jenis_nota_id'=>92,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Pati',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'JL. Wahid Hasyim, No. 22, Batangan, Pati Kidul, Kec. Pati',
                'm_w_m_jenis_nota_id'=>72,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Sampangan',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Menoreh Raya No 69, Sampangan Semarang',
                'm_w_m_jenis_nota_id'=>84,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Tembalang',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Tirto Agung No.32, Pedalangan, Banyumanik, Kota Semarang',
                'm_w_m_jenis_nota_id'=>91,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kudus',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Lingkar Utara no. 3, Peganjaran, Bae, Kudus',
                'm_w_m_jenis_nota_id'=>52,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
        ]);
    }
}