<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MWTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    public function run()
    {
        DB::table('m_w')->truncate();
        DB::table('m_w')->insert(
            [
                [
                    "m_w_id" => 1,
                    "m_w_nama" => "kantor pusat",
                    "m_w_code" => "001",
                    "m_w_m_area_id" => 9,
                    "m_w_m_w_jenis_id" => 4,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kaliurang km 4.5 gang kinanthi no.19 yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 2,
                    "m_w_nama" => "training center 1",
                    "m_w_code" => "002",
                    "m_w_m_area_id" => 9,
                    "m_w_m_w_jenis_id" => 4,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kaliurang km 5 gang jeruk no.3 (belakang natasha) yogyakarta 55284",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 3,
                    "m_w_nama" => "kantor ss supply pusat",
                    "m_w_code" => "003",
                    "m_w_m_area_id" => 9,
                    "m_w_m_w_jenis_id" => 4,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. dumung no iiia, karanggayam, caturtunggal, kec. depok, kabupaten sleman, daerah istimewa yogyakarta 55281",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 4,
                    "m_w_nama" => "kantor ss supply solo",
                    "m_w_code" => "004",
                    "m_w_m_area_id" => 9,
                    "m_w_m_w_jenis_id" => 4,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. cendrawasih i no.44, gonilan, kec. kartasura, kabupaten sukoharjo, jawa tengah 57169",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 5,
                    "m_w_nama" => "kantor eksternal",
                    "m_w_code" => "005",
                    "m_w_m_area_id" => 9,
                    "m_w_m_w_jenis_id" => 4,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kaliurang km. 4,5 gang srikaloka no.17 depok, sleman, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 6,
                    "m_w_nama" => "kantor area jabodetabek",
                    "m_w_code" => "006",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 5,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kavling perkebunan 3 no. 333 panunggangan barat, cibodas, tangerang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 7,
                    "m_w_nama" => "wss kisamaun",
                    "m_w_code" => "007",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kisamaun no 233, sukasari, tangerang.",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 8,
                    "m_w_nama" => "wss kisamaun #2",
                    "m_w_code" => "008",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kisamaun no 233 pasar lama, tangerang (depan pdam)",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 9,
                    "m_w_nama" => "wss bsd",
                    "m_w_code" => "009",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "bumi serpong damai blok v2/23 sektor 1.2 tangerang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 10,
                    "m_w_nama" => "wss karawaci",
                    "m_w_code" => "010",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "ruko asiatic ji. permata sari b15 no 50, karawaci, tangerang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 11,
                    "m_w_nama" => "wss bintaro 1",
                    "m_w_code" => "011",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "ji. bintaro utama iii blok ap no 57 bintaro sektor 3, tangerang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 12,
                    "m_w_nama" => "wss citra raya",
                    "m_w_code" => "012",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "ruko blossom ville w1 no 20 citra raya, tangerang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 13,
                    "m_w_nama" => "wss l'agricola",
                    "m_w_code" => "013",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "ji. l'agricola, ruko l'agricola blok a15, kelapa dua, curug sangereng, tangerang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 14,
                    "m_w_nama" => "wss gading serpong",
                    "m_w_code" => "014",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "ji raya kelapa puan af1/19 ruko gading serpong summarecon, tangerang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 15,
                    "m_w_nama" => "wss bogor yasmin",
                    "m_w_code" => "015",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "ruko taman yasmin, jl. rkh abdulah bin nuh no 202 sektor 6, bogor barat, bogor",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 16,
                    "m_w_nama" => "wss greenville",
                    "m_w_code" => "016",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jln. greenvile blok bl no.3, duri kepa, kebon jeruk, jakarta barat",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 17,
                    "m_w_nama" => "wss palemsemi",
                    "m_w_code" => "017",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. parasel ruko madrid no 30. palemsemi, karawaci, tangerang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 18,
                    "m_w_nama" => "wss bintaro 2",
                    "m_w_code" => "018",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. bintaro utama iii blok ap no.58 bintaro sektor 3, tangerang.",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 19,
                    "m_w_nama" => "wss tanjung duren utara",
                    "m_w_code" => "019",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. tanjung duren utara no. 224 grogol-jakarta barat",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 20,
                    "m_w_nama" => "wss bekasi",
                    "m_w_code" => "020",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. jend. sudirman no. 16, kayuringin jaya, bekasi selatan jawa barat",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 21,
                    "m_w_nama" => "wss tamansari",
                    "m_w_code" => "021",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "pusat kuliner tamansari, jl. boulevard palem raya, lippo karawaci, tangerang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 22,
                    "m_w_nama" => "wss jatinangor",
                    "m_w_code" => "022",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kol. ahmad sam no.48 desa sayang, jatinangor, sumedang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 23,
                    "m_w_nama" => "wss bawean",
                    "m_w_code" => "023",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. bawean no.1, merdeka, sumur bandung, kota bandung, jawa barat.",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 24,
                    "m_w_nama" => "wss depok margonda",
                    "m_w_code" => "024",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. margonda raya no.280, kemiri muka, beji, kota depok",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 25,
                    "m_w_nama" => "wss depok sawangan",
                    "m_w_code" => "025",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 7,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. raya sawangan no.63, mampang, kec. pancoran mas, kota depok, jawa barat 16435",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 26,
                    "m_w_nama" => "wss bogor ahmad yani",
                    "m_w_code" => "026",
                    "m_w_m_area_id" => 1,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. ahmad yani no 76 rt 02/02 kel. tanah sareal kec. tanah sareal-kota bogor-jawa barat",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 27,
                    "m_w_nama" => "kantor area purwokerto",
                    "m_w_code" => "027",
                    "m_w_m_area_id" => 2,
                    "m_w_m_w_jenis_id" => 5,
                    "m_w_status" => 1,
                    "m_w_alamat" => "perumahan kober indah no.123, gang riswan, jl. srempeng wetan no ii rt.04/rw.08, kelurahn kober, kec.purwokerto barat, banyumas, jawa tengah",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 28,
                    "m_w_nama" => "wss tegal",
                    "m_w_code" => "028",
                    "m_w_m_area_id" => 2,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kapten soedibyo no 220 , tegal selatan, tegal",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 29,
                    "m_w_nama" => "wss cirebon ampera",
                    "m_w_code" => "029",
                    "m_w_m_area_id" => 2,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. ampera raya no.11a, pekiringan, kesambi, kota cirebon",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 30,
                    "m_w_nama" => "wss cirebon tuparev",
                    "m_w_code" =>"030",
                    "m_w_m_area_id" => 2,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. tuparev (samping sentral yamaha), kesambi, cirebon",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 31,
                    "m_w_nama" => "wss purwokerto gor satria",
                    "m_w_code" => "031",
                    "m_w_m_area_id" => 2,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. prof. dr. soeharso, (depan pintu barat gor satria), purwokerto",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 32,
                    "m_w_nama" => "wss purwokerto wiryaatmaja",
                    "m_w_code" => "032",
                    "m_w_m_area_id" => 2,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. ra. wiryaatmaja (jl. bank) kel kedungwuluh, purwokerto barat",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 33,
                    "m_w_nama" => "wss cilacap",
                    "m_w_code" => "033",
                    "m_w_m_area_id" => 2,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl mt haryono no.31 (sebelah  dishub), cilacap selatan",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 34,
                    "m_w_nama" => "wss tasikmalaya",
                    "m_w_code" => "034",
                    "m_w_m_area_id" => 2,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. sutisna senjaya no. 189 kel. cikalang, kec. tawang, tasikmalaya",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 35,
                    "m_w_nama" => "wss wonosobo",
                    "m_w_code" => "035",
                    "m_w_m_area_id" => 2,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jln raya parakan - wonosobo no.23 karangluhur, kenteng, bojasari, kec. kertek, kabupaten wonosobo, jawa tengah 56371",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 36,
                    "m_w_nama" => "kantor area semarang",
                    "m_w_code" => "036",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 5,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. lamper tengah gang viii rt.07/rw.07 no.35 kelurahan lamper tengah, semarang selatan 50248",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 37,
                    "m_w_nama" => "wss sompok",
                    "m_w_code" => "037",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. sompok no 22, semarang selatan, semarang",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 38,
                    "m_w_nama" => "wss banyumanik",
                    "m_w_code" => "038",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jalan durian selatan i no. 29, srondol wetan, banyumanik, semarang",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 39,
                    "m_w_nama" => "wss puri anjasmoro",
                    "m_w_code" => "039",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. puri anjasmoro raya no 49, semarang barat, semarang",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 40,
                    "m_w_nama" => "wss sambiroto",
                    "m_w_code" => "040",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. sambiroto raya no f5 (ruko sambiroto) semarang",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 41,
                    "m_w_nama" => "wss lampersari",
                    "m_w_code" => "041",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. lamper sari no.29, lamper kidul, semarang selatan, kota semarang",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 42,
                    "m_w_nama" => "wss ngaliyan",
                    "m_w_code" => "042",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. prof. dr hamka no 59, semarang barat,ngaliyan, semarang",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 43,
                    "m_w_nama" => "wss salatiga diponegoro",
                    "m_w_code" => "043",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. diponegoro no 105, ruko wijaya square a1, sidorejo, kota salatiga,",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 44,
                    "m_w_nama" => "wss salatiga sudirman",
                    "m_w_code" => "044",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. jend. sudirman no 286, mrican, salatiga",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 45,
                    "m_w_nama" => "wss pekalongan",
                    "m_w_code" => "045",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. sapu garut no. 130, buaran, pekalongan",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 46,
                    "m_w_nama" => "wss ungaran",
                    "m_w_code" => "046",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. gatot subroto no 6 (jl.raya ungaran-semarang), bandarjo, ungaran barat",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 47,
                    "m_w_nama" => "wss pati",
                    "m_w_code" => "047",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. wahid hasyim, no. 22, batangan, pati kidul, kec. pati",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 48,
                    "m_w_nama" => "wss sampangan",
                    "m_w_code" => "048",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. menoreh raya no 69, sampangan semarang",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 49,
                    "m_w_nama" => "wss tembalang",
                    "m_w_code" => "049",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. tirto agung no.32, pedalangan, banyumanik, kota semarang",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 50,
                    "m_w_nama" => "wss kudus",
                    "m_w_code" => "050",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. lingkar utara no. 3, peganjaran, bae, kudus",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 51,
                    "m_w_nama" => "wss bawen",
                    "m_w_code" => "051",
                    "m_w_m_area_id" => 3,
                    "m_w_m_w_jenis_id" => 7,
                    "m_w_status" => 1,
                    "m_w_alamat" => "dusun ling merak. rejo rt 2 rw 8  kel harjo sari kcn bawen.  kab semarang.",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 52,
                    "m_w_nama" => "kantor area jogja",
                    "m_w_code" => "052",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 5,
                    "m_w_status" => 1,
                    "m_w_alamat" => "pogung rejo rt 14 /rw 51 no.414 sinduadi, mlati, sleman, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 53,
                    "m_w_nama" => "wss perjuangan",
                    "m_w_code" => "053",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kaliurang km 3, barat grha sabha pramana ugm, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 54,
                    "m_w_nama" => "wss condong catur barat",
                    "m_w_code" => "054",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. ringroad utara, condong catur, depok, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 55,
                    "m_w_nama" => "wss condong catur timur",
                    "m_w_code" => "055",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "ji. ringroad utara (200 m barat polda yogyakarta), condong catur, depok, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 56,
                    "m_w_nama" => "wss pandega martha",
                    "m_w_code" => "056",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. pandega marta, mlati, sleman, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 57,
                    "m_w_nama" => "wss samirono",
                    "m_w_code" => "057",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "ji. samirono baru (depan gor uny), gondokusuman, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 59,
                    "m_w_nama" => "wss gedongkuning",
                    "m_w_code" => "059",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jalan raya janti (seberang bkpm), banguntapan, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 60,
                    "m_w_nama" => "wss plengkung gading",
                    "m_w_code" => "060",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. mayjen sutoyo no 56, mantrijeron, depan bank bni, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 61,
                    "m_w_nama" => "wss veteran",
                    "m_w_code" => "061",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "ji. veteran no 122, warungboto, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 62,
                    "m_w_nama" => "wss monjali",
                    "m_w_code" => "062",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. monjali, karangjati, mlati, sleman, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 63,
                    "m_w_nama" => "wss maguwoharjo",
                    "m_w_code" => "063",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. utara stadion karangsari, wedomartani, kec. ngemplak, kabupaten sleman, daerah istimewa yogyakarta 55271",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 65,
                    "m_w_nama" => "wss bantul",
                    "m_w_code" => "065",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. raya bantul km. 6, sewon, bantul, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 66,
                    "m_w_nama" => "wss kyai mojo",
                    "m_w_code" => "066",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kyai mojo no. a68 pingit, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 67,
                    "m_w_nama" => "wss megatruh",
                    "m_w_code" => "067",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kaliurang km. 5 gang. megatruh no. 5 sleman yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 68,
                    "m_w_nama" => "ss express megatruh",
                    "m_w_code" => "068",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kaliurang km. 5 gang. megatruh no. 5 sleman yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 69,
                    "m_w_nama" => "wss kledokan",
                    "m_w_code" => "069",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. raya kledokan, caturtunggal, kec. depok, kabupaten sleman, daerah istimewa yogyakarta 55281",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 70,
                    "m_w_nama" => "dapur 1 yogyakarta",
                    "m_w_code" => "070",
                    "m_w_m_area_id" => 5,
                    "m_w_m_w_jenis_id" => 6,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. pogung rejo no.415, pogung kidul, sinduadi, kec. mlati, kabupaten sleman, daerah istimewa yogyakarta 55284",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 71,
                    "m_w_nama" => "kantor area perintis",
                    "m_w_code" => "071",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 5,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kaliurang km. 12 no. 42 sardonoharjo, ngaglik, sleman, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 72,
                    "m_w_nama" => "wss sewon",
                    "m_w_code" => "072",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. parangtritis km. 9 sewon, bantul, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 73,
                    "m_w_nama" => "wss magelang",
                    "m_w_code" => "073",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jalan tentara pelajar no. 20, kemirirejo, magelang",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 74,
                    "m_w_nama" => "wss prambanan",
                    "m_w_code" => "074",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jalan raya jogja - solo, sri mulyo, kebondalem kidul, prambanan",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 75,
                    "m_w_nama" => "wss palagan",
                    "m_w_code" => "075",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. palagan tentara pelajar km.7 no. 20a, yogyakarta.",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 76,
                    "m_w_nama" => "wss wonosari",
                    "m_w_code" => "076",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. baron km 1, siraman, wonosari, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 77,
                    "m_w_nama" => "wss temanggung",
                    "m_w_code" => "077",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 7,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jln gatot subroto no.30 manding,temanggung,temanggung",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 78,
                    "m_w_nama" => "wss kupatan",
                    "m_w_code" => "078",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 7,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. ahmad yani 340 magelang (depan rsj dr. soerojo)",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 79,
                    "m_w_nama" => "wss muntilan",
                    "m_w_code" => "079",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 7,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. bima,sayangan, muntilan, kauman, muntilan, magelang",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 80,
                    "m_w_nama" => "wss ambarketawang",
                    "m_w_code" => "080",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. wates no.km 6, depok, ambarketawang, kec. gamping, kabupaten sleman, daerah istimewa yogyakarta 55293",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 81,
                    "m_w_nama" => "wss tekim",
                    "m_w_code" => "081",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "universitas gajah mada",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 82,
                    "m_w_nama" => "wss jakal km 12",
                    "m_w_code" => "082",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kaliurang km. 12 no. 42 sardonoharjo, ngaglik, sleman, yogyakarta",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 83,
                    "m_w_nama" => "wss kulonprogo",
                    "m_w_code" => "083",
                    "m_w_m_area_id" => 4,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. kolonel sugiono no.16, gadingan, wates, kulon progo, yogyakarata 55651",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 84,
                    "m_w_nama" => "kantor area solo",
                    "m_w_code" => "084",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 5,
                    "m_w_status" => 1,
                    "m_w_alamat" => "griya permata 2 no. 1, gajahan, colomadu, karanganyar",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 85,
                    "m_w_nama" => "wss boyolali perintis",
                    "m_w_code" => "085",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "ji. perintis kemerdekaan no 889, boyolali",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 86,
                    "m_w_nama" => "wss sragen",
                    "m_w_code" => "086",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. brigjen slamet riyadi no. 105, pengko, sragen tengah, sragen",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 87,
                    "m_w_nama" => "wss karanganyar",
                    "m_w_code" => "087",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. brigjen slamet riyadi, badran mulyo, karanganyar. (sebelah utara spbu lalung)",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 88,
                    "m_w_nama" => "wss patimura",
                    "m_w_code" => "088",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. patimura no.91 dawung tengah, serengan, solo.",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 89,
                    "m_w_nama" => "wss manahan barat",
                    "m_w_code" => "089",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "ji. hasanudin no 53, laweyan, solo",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 90,
                    "m_w_nama" => "wss gonilan",
                    "m_w_code" => "090",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. melon raya, karangasem, solo. (belakang taman edupark ums)",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 91,
                    "m_w_nama" => "wss solo baru",
                    "m_w_code" => "091",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. raya solo baru, bacem no.8r langenharjo, grogol, sukoharjo (sebelum pertigaan jembatan bacem)",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 92,
                    "m_w_nama" => "wss jurug",
                    "m_w_code" => "092",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl.ir. sutami no.13a, kentingan, surakarta (sebelah selatan spbu sekarpace)",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 93,
                    "m_w_nama" => "wss kerten",
                    "m_w_code" => "093",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. blimbing no. 5 (belakang rs panti waluyo), kerten",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 94,
                    "m_w_nama" => "wss klaten",
                    "m_w_code" => "094",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. mayor kusmanto, dukuh sekar mulyo, rt 02 rw 07 desa sekarsuli , klaten.",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 95,
                    "m_w_nama" => "wss wonogiri",
                    "m_w_code" => "095",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. ahmad yani no 98, kp kerdu kepik, kel. giripurwo,(dpn tk kerudung rabbani)",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 96,
                    "m_w_nama" => "wss manahan timur",
                    "m_w_code" => "096",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "ji. hasanudin no 53, laweyan, solo",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 97,
                    "m_w_nama" => "wss boyolali heritage",
                    "m_w_code" => "097",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. merbabu no 31, wisma heritage, boyolali",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 98,
                    "m_w_nama" => "wss banyudono",
                    "m_w_code" => "098",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 1,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. raya boyolali - solo km.10 kuwiran, banyudono, boyolali",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 99,
                    "m_w_nama" => "wss kopral sayom",
                    "m_w_code" => "099",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jln kopral sayom no 23, jetak kidul ,karanganom,klaten utara, jawa tengah",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 100,
                    "m_w_nama" => "dapur 1 solo",
                    "m_w_code" => "100",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 6,
                    "m_w_status" => 1,
                    "m_w_alamat" => "gatak, gajahan, kec. colomadu, kabupaten karanganyar, jawa tengah 57176",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 101,
                    "m_w_nama" => "wss klodran",
                    "m_w_code" => "101",
                    "m_w_m_area_id" => 6,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. adi sumarmo no.337, plalangan, klodran, kec. colomadu, kabupaten karanganyar, jawa tengah 57172",
                    "m_w_m_kode_nota" => "nota b",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 102,
                    "m_w_nama" => "kantor area malang",
                    "m_w_code" => "102",
                    "m_w_m_area_id" => 7,
                    "m_w_m_w_jenis_id" => 5,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. maninjau raya no.09 kedung kandang, sawo jajar, malang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 103,
                    "m_w_nama" => "wss kediri",
                    "m_w_code" => "103",
                    "m_w_m_area_id" => 7,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. letjend suparman no.60, tosaren,  kota kediri",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 104,
                    "m_w_nama" => "wss malang sengkaling",
                    "m_w_code" => "104",
                    "m_w_m_area_id" => 7,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. sengkaling no. 150, malang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 105,
                    "m_w_nama" => "wss malang ciliwung",
                    "m_w_code" => "105",
                    "m_w_m_area_id" => 7,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. ciliwung no. 53, malang",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 106,
                    "m_w_nama" => "wss jember",
                    "m_w_code" => "106",
                    "m_w_m_area_id" => 7,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. danau toba no. 15, tegal gede, sumber, jember",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 107,
                    "m_w_nama" => "wss madiun",
                    "m_w_code" => "107",
                    "m_w_m_area_id" => 7,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. h. agus salim no. 180, manguharjo, madiun",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 108,
                    "m_w_nama" => "wss surabaya #1 arjuna raya",
                    "m_w_code" => "108",
                    "m_w_m_area_id" => 7,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. arjuna raya gg. merapi no. 12-14, sawahan",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 109,
                    "m_w_nama" => "wss malang la sucipto",
                    "m_w_code" => "109",
                    "m_w_m_area_id" => 7,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. laksda adi sucipto no.75, jawa timur 65125",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 110,
                    "m_w_nama" => "wss surabaya #3 rungkut",
                    "m_w_code" => "110",
                    "m_w_m_area_id" => 7,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jalan rungkut madya no. 25, rungkut kidul, surabaya",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 111,
                    "m_w_nama" => "kantor area bali",
                    "m_w_code" => "111",
                    "m_w_m_area_id" => 8,
                    "m_w_m_w_jenis_id" => 5,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. tukad pakerisan gg.xiv no.4 panjer, renon, denpasar selatan",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 112,
                    "m_w_nama" => "wss bali batubulan",
                    "m_w_code" => "112",
                    "m_w_m_area_id" => 8,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. raya batubulan - gianyar (utara lapangan candra muka), batubulan, gianyar",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 113,
                    "m_w_nama" => "wss bali tukad barito",
                    "m_w_code" => "113",
                    "m_w_m_area_id" => 8,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. tukad barito no. 30-31 renon, denpasar",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 114,
                    "m_w_nama" => "wss bali uluwatu",
                    "m_w_code" => "114",
                    "m_w_m_area_id" => 8,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. pura masuka no. 1, ungasan, uluwatu, badung selatan, bali",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 115,
                    "m_w_nama" => "wss bali gatot subroto",
                    "m_w_code" => "115",
                    "m_w_m_area_id" => 8,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. gatot subroto barat no.456, padangsambian kaja, kec. denpasar bar., kota denpasar, bali 80118",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 116,
                    "m_w_nama" => "wss bali teuku umar",
                    "m_w_code" => "116",
                    "m_w_m_area_id" => 8,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. teuku umar barat no. 355, denpasar, bali",
                    "m_w_m_kode_nota" => "nota a",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 117,
                    "m_w_nama" => "kantor area malaysia",
                    "m_w_code" => "117",
                    "m_w_m_area_id" => 11,
                    "m_w_m_w_jenis_id" => 5,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. wan kadir 2, taman tun dr. ismail, ruko no  43 kuala lumpur",
                    "m_w_m_kode_nota" => "nota c",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
                [
                    "m_w_id" => 118,
                    "m_w_nama" => "wss ttdi kuala lumpur",
                    "m_w_code" => "118",
                    "m_w_m_area_id" => 11,
                    "m_w_m_w_jenis_id" => 2,
                    "m_w_status" => 1,
                    "m_w_alamat" => "jl. wan kadir 2, taman tun dr. ismail, ruko no  43 kuala lumpur",
                    "m_w_m_kode_nota" => "nota c",
                    "m_w_m_pajak_id" => 2,
                    "m_w_m_modal_tipe_id" => 3,
                    "m_w_m_sc_id" => 1,
                    "m_w_decimal" => 2,
                    "m_w_pembulatan" => "ya",
                    "m_w_currency" => "Rp",
                    "m_w_created_by" => 1,
                ],
            ]
        );
    }
}
