<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
class MWTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('m_w')->truncate();
        DB::table('m_w')->insert([
            [  
                'm_w_nama' =>'WSS Wonosobo',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jln Raya Parakan - Wonosobo No.23 Karangluhur, Kenteng, Bojasari,Kec. Kertek, Kabupaten Wonosobo, Jawa Tengah 56371',
                'm_w_m_jenis_nota_id'=>96,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Tasikmalaya',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'	Jl. Sutisna Senjaya No. 189 Kel. Cikalang, Kec. Tawang, Tasikmalaya',
                'm_w_m_jenis_nota_id'=>25,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Tegal',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kapten Soedibyo No 220 , Tegal Selatan, Tegal',
                'm_w_m_jenis_nota_id'=>89,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS GOR Satria',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Prof. DR. Soeharso, (Depan Pintu Barat GOR Satria), Purwokerto',
                'm_w_m_jenis_nota_id'=>78,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS WSS Cirebon Ampera',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Ampera Raya No.11A, Pekiringan, Kesambi, Kota Cirebon',
                'm_w_m_jenis_nota_id'=>36,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Cirebon Tuparev',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Tuparev (Samping Sentral Yamaha), Kesambi, Cirebon',
                'm_w_m_jenis_nota_id'=>37,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Wiryaatmaja',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. RA. Wiryaatmaja (Jl. Bank) Kel Kedungwuluh, Purwokerto Barat',
                'm_w_m_jenis_nota_id'=>79,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Cilacap',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl MT Haryono No.31 (Sebelah DISHUB), Cilacap Selatan',
                'm_w_m_jenis_nota_id'=>35,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bali Gatot Subroto',
                'm_w_m_area_id'=>8,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Gatot Subroto Barat No.456, Padangsambian Kaja, Kec. Denpasar Bar., Kota Denpasar, Bali 80118',
                'm_w_m_jenis_nota_id'=>5,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Teuku Umar',
                'm_w_m_area_id'=>8,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Teuku Umar Barat No. 355, Denpasar, Bali',
                'm_w_m_jenis_nota_id'=>2,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bali Batubulan',
                'm_w_m_area_id'=>8,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Raya Batubulan - Gianyar (utara Lapangan Candra Muka), Batubulan, Gianyar',
                'm_w_m_jenis_nota_id'=>4,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bali Tukad Barito',
                'm_w_m_area_id'=>8,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Tukad Barito No. 30-31 Renon, Denpasar',
                'm_w_m_jenis_nota_id'=>3,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bali Uluwatu',
                'm_w_m_area_id'=>8,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Pura Masuka no. 1, Ungasan, Uluwatu, Badung Selatan, Bali',
                'm_w_m_jenis_nota_id'=>1,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Depok Sawangan',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Raya Sawangan No.63, Mampang, Kec. Pancoran Mas, Kota Depok, Jawa Barat 16435',
                'm_w_m_jenis_nota_id'=>15,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bogor Ahmad Yani',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Ahmad Yani No 76 RT 02/02 Kel. Tanah Sareal Kec. Tanah Sareal-Kota Bogor-Jawa Barat',
                'm_w_m_jenis_nota_id'=>11,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kisamaun 1',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kisamaun No 233, Sukasari, Tangerang.',
                'm_w_m_jenis_nota_id'=>19,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kisamaun 2',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kisamaun No 233 Pasar Lama, Tangerang (Depan PDAM)',
                'm_w_m_jenis_nota_id'=>20,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS BSD',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Bumi Serpong Damai Blok V2/23 sektor 1.2 Tangerang',
                'm_w_m_jenis_nota_id'=>12,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Karawaci',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Ruko Asiatic JI. Permata Sari B15 No 50, Karawaci, Tangerang',
                'm_w_m_jenis_nota_id'=>18,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bintaro 1',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'JI. Bintaro Utama III Blok AP No 57 Bintaro Sektor 3, Tangerang',
                'm_w_m_jenis_nota_id'=>8,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bintaro 2',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Bintaro Utama III Blok AP No.58 Bintaro Sektor 3, Tangerang.',
                'm_w_m_jenis_nota_id'=>9,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Citra Raya',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Ruko Blossom Ville W1 No 20 Citra Raya, Tangerang',
                'm_w_m_jenis_nota_id'=>13,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Agricola',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'JI. Agricola, Ruko Agricola Blok A15, Kelapa Dua, Curug sangereng, Tangerang',
                'm_w_m_jenis_nota_id'=>21,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Gading Serpong',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'JI Raya Kelapa Puan AF1/19 Ruko Gading Serpong Summarecon, Tangerang',
                'm_w_m_jenis_nota_id'=>16,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bogor Yasmin',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Ruko Taman Yasmin, Jl. RKH Abdulah Bin Nuh No 202 Sektor 6, Bogor Barat, Bogor',
                'm_w_m_jenis_nota_id'=>10,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Greenville',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jln. Greenvile Blok BL No.3, Duri Kepa, Kebon Jeruk, Jakarta Barat',
                'm_w_m_jenis_nota_id'=>17,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Palemsemi',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Parasel Ruko Madrid No 30. Palemsemi, Karawaci, Tangerang',
                'm_w_m_jenis_nota_id'=>22,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Tanjung Duren Utara',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Tanjung Duren Utara No. 224 Grogol-Jakarta Barat',
                'm_w_m_jenis_nota_id'=>24,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bekasi',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Jend. Sudirman No. 16, Kayuringin Jaya, Bekasi Selatan Jawa Barat',
                'm_w_m_jenis_nota_id'=>7,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Tamansari',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Pusat Kuliner Tamansari, Jl. Boulevard Palem Raya, Lippo Karawaci, Tangerang',
                'm_w_m_jenis_nota_id'=>23,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Jatinangor',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kol. Ahmad Sam No.48 Desa Sayang, Jatinangor, Sumedang',
                'm_w_m_jenis_nota_id'=>97,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bawean',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Bawean No.1, Merdeka, Sumur Bandung, Kota Bandung, Jawa Barat.',
                'm_w_m_jenis_nota_id'=>6,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Depok',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Margonda Raya No.280, Kemiri Muka, Beji, Kota Depok',
                'm_w_m_jenis_nota_id'=>14,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kediri',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Letjend Suparman No.60, Tosaren,  Kota Kediri',
                'm_w_m_jenis_nota_id'=>47,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Malang Sengkaling',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Sengkaling No. 150, Malang',
                'm_w_m_jenis_nota_id'=>62,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Malang Ciliwung',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Ciliwung No. 53, Malang',
                'm_w_m_jenis_nota_id'=>60,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Jember',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Danau Toba No. 15, Tegal Gede, Sumber, Jember',
                'm_w_m_jenis_nota_id'=>44,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Madiun',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. H. Agus Salim No. 180, Manguharjo, Madiun',
                'm_w_m_jenis_nota_id'=>57,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Arjuna Raya',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Arjuna Raya Gg. Merapi No. 12-14, Sawahan',
                'm_w_m_jenis_nota_id'=>26,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Rungkut',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jalan Rungkut Madya no. 25, Rungkut Kidul, Surabaya',
                'm_w_m_jenis_nota_id'=>27,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Malang LA Sucipto',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Laksda Adi Sucipto No.75, Jawa Timur 65125',
                'm_w_m_jenis_nota_id'=>61,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kulonprogo',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kolonel Sugiono No.16, Gadingan, Wates, Kulon Progo, Yogyakarata 55651',
                'm_w_m_jenis_nota_id'=>53,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Ambarketawang',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Wates No.Km 6, Depok, Ambarketawang, Kec. Gamping, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55293',
                'm_w_m_jenis_nota_id'=>28,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Jakal Km 12',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kaliurang Km. 12 No. 42 Sardonoharjo, Ngaglik, Sleman, Yogyakarta',
                'm_w_m_jenis_nota_id'=>43,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Tekim',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Universitas Gajah Mada',
                'm_w_m_jenis_nota_id'=>98,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Sewon',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Parangtritis Km. 9 Sewon, Bantul, Yogyakarta',
                'm_w_m_jenis_nota_id'=>85,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Magelang',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jalan Tentara Pelajar No. 20, Kemirirejo, Magelang',
                'm_w_m_jenis_nota_id'=>58,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Prambanan',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jalan Raya Jogja - Solo, Sri Mulyo, Kebondalem Kidul, Prambanan',
                'm_w_m_jenis_nota_id'=>76,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Palagan',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Palagan Tentara Pelajar km.7 no. 20A, Yogyakarta.',
                'm_w_m_jenis_nota_id'=>69,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Wonosari',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Baron Km 1, Siraman, Wonosari, Yogyakarta',
                'm_w_m_jenis_nota_id'=>95,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Temanggung',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jln Gatot Subroto no.30 Manding,temanggung,temanggung',
                'm_w_m_jenis_nota_id'=>90,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kupatan',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Ahmad Yani 340 Magelang (Depan RSJ Dr. Soerojo)',
                'm_w_m_jenis_nota_id'=>54,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Muntilan',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Bima,Sayangan, Muntilan, Kauman, Muntilan, Magelang',
                'm_w_m_jenis_nota_id'=>67,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Sompok',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Sompok No 22, Semarang Selatan, Semarang',
                'm_w_m_jenis_nota_id'=>87,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Banyumanik',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jalan Durian Selatan I No. 29, Srondol Wetan, Banyumanik, Semarang',
                'm_w_m_jenis_nota_id'=>31,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Puri Anjasmoro',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Puri Anjasmoro Raya No 49, Semarang Barat, Semarang',
                'm_w_m_jenis_nota_id'=>77,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Sambiroto',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Sambiroto Raya No F5 (Ruko Sambiroto) Semarang',
                'm_w_m_jenis_nota_id'=>82,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Lampersari',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Lamper Sari No.29, Lamper Kidul, Semarang Selatan, Kota Semarang',
                'm_w_m_jenis_nota_id'=>56,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Ngaliyan',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Prof. Dr Hamka No 59, Semarang Barat,Ngaliyan, Semarang',
                'm_w_m_jenis_nota_id'=>68,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Salatiga Diponegoro',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Diponegoro No 105, Ruko wijaya Square A1, Sidorejo, Kota Salatiga',
                'm_w_m_jenis_nota_id'=>80,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Salatiga Sudirman',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Jend. Sudirman No 286, Mrican, Salatiga',
                'm_w_m_jenis_nota_id'=>81,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Pekalongan',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Sapu Garut no. 130, Buaran, Pekalongan',
                'm_w_m_jenis_nota_id'=>74,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Ungaran',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Gatot Subroto No 6 (Jl.Raya Ungaran-Semarang), Bandarjo, Ungaran barat',
                'm_w_m_jenis_nota_id'=>92,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Pati',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'JL. Wahid Hasyim, No. 22, Batangan, Pati Kidul, Kec. Pati',
                'm_w_m_jenis_nota_id'=>72,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Sampangan',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Menoreh Raya No 69, Sampangan Semarang',
                'm_w_m_jenis_nota_id'=>84,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Tembalang',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Tirto Agung No.32, Pedalangan, Banyumanik, Kota Semarang',
                'm_w_m_jenis_nota_id'=>91,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kudus',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Lingkar Utara no. 3, Peganjaran, Bae, Kudus',
                'm_w_m_jenis_nota_id'=>52,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Klodran',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Adi Sumarmo No.337, Plalangan, Klodran, Kec. Colomadu, Kabupaten Karanganyar, Jawa Tengah 57172',
                'm_w_m_jenis_nota_id'=>99,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kopral Sayom',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jln Kopral Sayom No 23, Jetak kidul ,Karanganom,Klaten utara, Jawa tengah',
                'm_w_m_jenis_nota_id'=>51,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Wonogiri',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Ahmad Yani No 98, Kp Kerdu Kepik, Kel. Giripurwo,(dpn tk kerudung rabbani)',
                'm_w_m_jenis_nota_id'=>94,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Klaten',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Mayor Kusmanto, Dukuh Sekar Mulyo, RT 02 RW 07 Desa Sekarsuli , Klaten.',
                'm_w_m_jenis_nota_id'=>49,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Boyolali Perintis',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'JI. Perintis Kemerdekaan No 889, Boyolali',
                'm_w_m_jenis_nota_id'=>34,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Sragen',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Brigjen Slamet Riyadi no. 105, Pengko, Sragen Tengah, Sragen',
                'm_w_m_jenis_nota_id'=>88,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Karanganyar',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Brigjen Slamet Riyadi, Badran Mulyo, Karanganyar. (sebelah utara SPBU Lalung)',
                'm_w_m_jenis_nota_id'=>46,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Patimura',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Patimura no.91 Dawung Tengah, Serengan, Solo.',
                'm_w_m_jenis_nota_id'=>73,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Manahan Barat',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'JI. Hasanudin No 53, Laweyan, Solo',
                'm_w_m_jenis_nota_id'=>63,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Gonilan',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Melon Raya, Karangasem, Solo. (belakang taman Edupark UMS)',
                'm_w_m_jenis_nota_id'=>42,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Solo Baru',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Raya Solo Baru, Bacem No.8R Langenharjo, Grogol, Sukoharjo (Sebelum Pertigaan Jembatan Bacem)',
                'm_w_m_jenis_nota_id'=>86,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Jurug',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl.Ir. Sutami No.13A, Kentingan, Surakarta (sebelah selatan SPBU Sekarpace)',
                'm_w_m_jenis_nota_id'=>45,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kerten',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Blimbing no. 5 (Belakang RS Panti Waluyo), Kerten',
                'm_w_m_jenis_nota_id'=>48,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Manahan Timur',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'JI. Hasanudin No 53, Laweyan, Solo',
                'm_w_m_jenis_nota_id'=>64,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Boyolali Heritage',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Merbabu No 31, Wisma Heritage, Boyolali',
                'm_w_m_jenis_nota_id'=>34,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Banyudono',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Raya Boyolali - Solo Km.10 Kuwiran, Banyudono, Boyolali',
                'm_w_m_jenis_nota_id'=>30,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'SS Express Megatruh',
                'm_w_m_area_id'=>5,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kaliurang Km. 5 Gang. Megatruh No. 5 Sleman Yogyakarta',
                'm_w_m_jenis_nota_id'=>100,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kledokan',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Raya Kledokan, Caturtunggal, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55281',
                'm_w_m_jenis_nota_id'=>50,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Perjuangan',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kaliurang Km 3, Barat Grha Sabha Pramana UGM, Yogyakarta',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>1,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Condong Catur Barat',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Ringroad Utara, Condong Catur, Depok, Yogyakarta',
                'm_w_m_jenis_nota_id'=>38,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Condong Catur Timur',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'JI. Ringroad Utara (200 m barat POLDA Yogyakarta), Condong Catur, Depok, Yogyakarta',
                'm_w_m_jenis_nota_id'=>39,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Pandega Martha',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Pandega Marta, Mlati, Sleman, Yogyakarta',
                'm_w_m_jenis_nota_id'=>71,
                'm_w_m_pajak_id'=>1,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Samirono',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'JI. Samirono Baru (depan GOR UNY), Gondokusuman, Yogyakarta',
                'm_w_m_jenis_nota_id'=>83,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Gedongkuning',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jalan Raya Janti (seberang BKPM), Banguntapan, Yogyakarta',
                'm_w_m_jenis_nota_id'=>41,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Plengkung Gading',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Mayjen Sutoyo No 56, Mantrijeron, Depan Bank BNI, Yogyakarta',
                'm_w_m_jenis_nota_id'=>75,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Veteran',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'JI. Veteran No 122, Warungboto, Yogyakarta',
                'm_w_m_jenis_nota_id'=>93,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Monjali',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Monjali, Karangjati, Mlati, Sleman, Yogyakarta',
                'm_w_m_jenis_nota_id'=>66,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Maguwoharjo',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Utara Stadion Karangsari, Wedomartani, Kec. Ngemplak, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55271',
                'm_w_m_jenis_nota_id'=>59,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bantul',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Raya Bantul Km. 6, Sewon, Bantul, Yogyakarta',
                'm_w_m_jenis_nota_id'=>29,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Kyai Mojo',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kyai Mojo no. A68 Pingit, Yogyakarta',
                'm_w_m_jenis_nota_id'=>55,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Megatruh',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kaliurang Km. 5 Gang. Megatruh No. 5 Sleman Yogyakarta',
                'm_w_m_jenis_nota_id'=>65,
                'm_w_m_pajak_id'=>1,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Jakal 8',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>1,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kaliurang Km. 9 (Kompleks DeHalal Mart), Sardonoharjo, Sleman, Yogyakarta',
                'm_w_m_jenis_nota_id'=>40,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'WSS Bawen',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>2,
                'm_w_status'=>1,
                'm_w_alamat'=>'Dusun Ling merak. Rejo RT 2 RW 8  Kel harjo sari Kcn Bawen.  Kab Semarang.',
                'm_w_m_jenis_nota_id'=>32,
                'm_w_m_pajak_id'=>2,
                'm_w_m_modal_tipe_id'=>3,
                'm_w_m_sc_id'=>1,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Kantor Area Bali',
                'm_w_m_area_id'=>8,
                'm_w_m_w_jenis_id'=>5,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Tukad Pakerisan Gg.XIV No.4 Panjer, Renon, Denpasar Selatan',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Kantor Area Jabodetabek',
                'm_w_m_area_id'=>1,
                'm_w_m_w_jenis_id'=>5,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kavling Perkebunan 3 No. 333 Panunggangan Barat, Cibodas, Tangerang',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Kantor Area Malang',
                'm_w_m_area_id'=>7,
                'm_w_m_w_jenis_id'=>5,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Maninjau Raya No.09 Kedung Kandang, Sawo Jajar, Malang',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Kantor Area Perintis',
                'm_w_m_area_id'=>4,
                'm_w_m_w_jenis_id'=>5,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kaliurang Km  4,5 Gang Grompol No.1 Depok, Sleman, Yogyakarta',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Kantor Area Purwokerto',
                'm_w_m_area_id'=>2,
                'm_w_m_w_jenis_id'=>5,
                'm_w_status'=>1,
                'm_w_alamat'=>'Perumahan Kober Indah No.123, Gang Riswan, Jl. Srempeng Wetan No II RT.04/RW.08, Kelurahn Kober, Kec.Purwokerto Barat, Banyumas, Jawa Tengah',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Kantor Area Semarang',
                'm_w_m_area_id'=>3,
                'm_w_m_w_jenis_id'=>5,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Lamper Tengah Gang VIII RT.07/RW.07 No.35 Kelurahan Lamper Tengah, Semarang Selatan 50248',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Kantor Area Solo',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>5,
                'm_w_status'=>1,
                'm_w_alamat'=>'JGriya Permata 2 No. 1, Gajahan, Colomadu, Karanganyar',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Kantor Area Jogja',
                'm_w_m_area_id'=>5,
                'm_w_m_w_jenis_id'=>5,
                'm_w_status'=>1,
                'm_w_alamat'=>'Pogung Rejo RT 14 /RW 51 No.414 Sinduadi, Mlati, Sleman, Yogyakarta',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Kantor Pusat',
                'm_w_m_area_id'=>11,
                'm_w_m_w_jenis_id'=>4,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kaliurang Km 4.5 Gang Kinanthi No.19 Yogyakarta',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Dapur 1 Solo',
                'm_w_m_area_id'=>6,
                'm_w_m_w_jenis_id'=>6,
                'm_w_status'=>1,
                'm_w_alamat'=>'Gatak, Gajahan, Kec. Colomadu, Kabupaten Karanganyar, Jawa Tengah 57176',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Dapur 1 Yogyakarta',
                'm_w_m_area_id'=>5,
                'm_w_m_w_jenis_id'=>6,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Pogung Rejo No.415, Pogung Kidul, Sinduadi, Kec. Mlati, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55284',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Training Center',
                'm_w_m_area_id'=>11,
                'm_w_m_w_jenis_id'=>4,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kaliurang Km 4.5 Gang Kinanthi No.19 Yogyakarta',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Kantor Eksternal',
                'm_w_m_area_id'=>9,
                'm_w_m_w_jenis_id'=>4,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Kaliurang Km 4.5 Gang Kinanthi No.19 Yogyakarta',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
            [  
                'm_w_nama' =>'Kantor SS Supply',
                'm_w_m_area_id'=>11,
                'm_w_m_w_jenis_id'=>4,
                'm_w_status'=>1,
                'm_w_alamat'=>'Jl. Dumung No IIIA, Karanggayam, Caturtunggal, Kec. Depok, Kabupaten Sleman, Daerah Istimewa Yogyakarta 55281',
                'm_w_m_jenis_nota_id'=>0,
                'm_w_m_pajak_id'=>0,
                'm_w_m_modal_tipe_id'=>0,
                'm_w_m_sc_id'=>0,
                'm_w_decimal'=>0,
                'm_w_pembulatan'=>'Tidak',
                'm_w_currency'=>'Rp',
                'm_w_grab'=>0,
                'm_w_gojek'=>0,
                'm_menu_profit'=>1,
                'm_w_created_by'=>1,
            ],
        ]);
    }
}